<ol class="breadcrumb">
    <li><a href="<?=$this->url('application/default', array('controller' => 'index'))?>">Início</a></li>
    <li class="active">Mensagens Recebidas</li>
</ol>
<br>

<form>
<div>
    Desejo receber e-mail para toda mensagem recebida no mural de mensagens do site:
    <br>
    <input type="radio" name="emailsim" value="1" checked> Sim
    <input type="radio" name="emailnao" value="0"> Não
</div>
</form>
<br>
<br>
<form>
<div>
    Desejo aprovar as mensagens antes de serem publicadas no mural de mensagens:
    <br>
    <input type="radio" name="aprovasim" value="1"> Sim
    <input type="radio" name="aprovanao" value="0" checked> Não
</div>
</form>