<ol class="breadcrumb">
    <li><a href="<?=$this->url('dashboard/default', array('controller' => 'index'))?>">Início</a></li>
    <li class="active">Planejador Financeiro</li>
</ol>

<a href="<?=$this->url('dashboard/default', array('controller' => 'planejador-financeiro', 'action' => 'adicionar-despesa'))?>" >
    <div>
        <span class="glyphicon glyphicon-plus btnDireita gi-2x" title="Adicionar Despesa"></span>        
    </div>
</a>
<br class="brBoth"><br>
<table class="table table-hover">
    <tr class="topoTabLista">
        <td><img alt="Varios check" title="clique aqui para marcar todas despesas" src="<?php echo $this->basePath('img/multiplosCheck.png') ?>" ></td>
        <td>Descrição</td>
        <td>Categoria</td>
        <td>Valor</td>
        <td>Compensado</td>
        <td>Quem Pagou?</td>
        <td>Ações</td>
    </tr>    
    <?php foreach ($this->lista as $f): ?>
    <tr>
        <td><input type="checkbox"></label></td>
        <td><?php echo $f->getDescricao() ?></td>
        <td><?php echo $f->getCategoria() ?></td>
        <td><?php echo $f->getValor() ?></td>
        <td><?php echo $f->getCompensado() ?></td>
        <td><?php echo $f->getQuemPagou() ?></td>
        <td>
            <span class="glyphicon glyphicon-pencil editarClIco"><span> | 
            <a href="<?=$this->url('route2', array('action' => 'deletar-despesa', 'id' => $f->getId()))?>"><span class="glyphicon glyphicon-trash excluirClIco"></a> <span>
        </td>
    </tr>
    <?php endforeach; ?>
</table>
<a href="<?=$this->url('dashboard/default', array('controller' => 'planejador-financeiro', 'action' => 'adicionar-despesa'))?>" >
    <div>
        <span class="glyphicon glyphicon-plus btnDireita gi-2x" title="Adicionar Despesa"></span>        
    </div>
</a>