<ol class="breadcrumb">
    <li><a href="<?=$this->url('dashboard/default', array('controller' => 'index'))?>">Início</a></li>
    <li class="active">Mensagens Recebidas</li>
</ol>
<br>

<div>
    Desejo receber uma notificação via e-mail quando receber uma mensagem no mural do site:
    <br>
    <label class="radio-inline"><input type="radio" value="1" name="enviaEmail">Sim</label>
    <label class="radio-inline"><input type="radio" value="0" name="enviaEmail" checked>Não</label>
</div>
<br>
<div>
    Desejo aprovar as mensagens antes de serem publicadas no mural de mensagens:
    <br>
    <label class="radio-inline"><input type="radio" value="1" name="aprovaMsg">Sim</label>
    <label class="radio-inline"><input type="radio" value="0" name="aprovaMsg" checked>Não</label>
</div>