<ol class="breadcrumb">
    <li><a href="<?=$this->url('dashboard/default', array('controller' => 'index'))?>">Início</a></li>
    <li class="active">Proteção por senha</li>
</ol>
<br>
Digite uma senha e confirme nos campos abaixo para que somente pessoas autorizadas acessem suas informações. 
Não esqueça de enviar a senha pelo convite.
<br><br>
<form>
    <div class="form-group">
      <label for="senhaSite1">Senha</label>
      <input type="password" class="form-control" id="exampleInputPassword1" placeholder="Senha">
    </div>
    <div class="form-group">
      <label for="senhaSite2">Confirmar Senha</label>
      <input type="password" class="form-control" id="exampleInputPassword1" placeholder="Confirmar Senha">
    </div>
    <div class="checkbox">
        <label>
          <input type="checkbox"> Desabilitar proteção de senha
        </label>
    </div>
    <button type="submit" class="btn btn-primary">Salvar</button>
</form>