<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('euCasando')?>
        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                ->prependStylesheet($this->basePath('css/estilos.css'))
                ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
                ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath('js/bootstrap.min.js'))
            ->prependFile('//code.jquery.com/jquery-migrate-1.2.1.min.js')
            ->prependFile('//code.jquery.com/jquery-1.11.3.min.js')
        ; ?>

    </head>
    <body>
        <nav class="navbar navbar-default">
            <div class="container-fluid">
              <!-- Brand and toggle get grouped for better mobile display -->
              <div class="navbar-header">
                <a class="navbar-brand" href="<?php echo $this->url('application/default', array('controller' => 'index', 'action' => 'index')); ?>">
                    <img alt="Brand" src="<?php echo $this->basePath('img/logo.png') ?>">
                </a>
              </div>
              <!-- Collect the nav links, forms, and other content for toggling -->
              <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                  <li class="active"><a href="#">Link <span class="sr-only">(current)</span></a></li>
                  <li><a href="#">Link</a></li>
                </ul>

                <ul class="nav navbar-nav navbar-right">
                  <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><span class="glyphicon glyphicon-user"></span>&nbsp;&nbsp;Alice Albuquerque<span class="caret"></span></a>
                    <ul class="dropdown-menu">
                      <li><a href="#">Perfil</a></li>
                      <li><a href="#">Plano</a></li>
                      <li><a href="#">Dados bancários</a></li>
                      <li><a href="#">Visitar Site</a></li>
                      <li role="separator" class="divider"></li>
                      <li><a href="#">Sair</a></li>
                    </ul>
                  </li>
                </ul>
              </div><!-- /.navbar-collapse -->
            </div><!-- /.container-fluid -->
        </nav>
        <div class="container">
            <?php echo $this->content; ?>
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
    </body>
</html>