<ol class="breadcrumb">
    <li><a href="<?=$this->url('dashboard/default', array('controller' => 'index'))?>">Início</a></li>
</ol>
<br>
Você tem direito a 15mb de espaço no servidor para construção do site.
<br><br>
<div class="progress">
    <div class="progress-bar progress-bar-striped" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" style="width: 60%;">
      60%
    </div>
</div>
<div class="espaco-livre">6000mb livres de 15mb</div>

<?php
//echo $this->retornaNomeCtrAct();
?>