<ol class="breadcrumb">
    <li><a href="<?=$this->url('dashboard/default', array('controller' => 'index'))?>">Início</a></li>
    <li class="active">Lista de Convidados</li>
</ol>

<table>
    <td>
        <ul class="list-group">
            <li class="list-group-item">
                <span class="badge"><?php echo $this->qtde_adultos ?></span>
                Adultos:&nbsp;&nbsp;
            </li>
        </ul>
    </td>
    <td>
        <ul class="list-group">
            <li class="list-group-item">
                <span class="badge"><?php echo $this->qtde_criancas ?></span>
                Crianças:&nbsp;&nbsp;
            </li>
        </ul>
    </td>
    <td>
        <ul class="list-group">
            <li class="list-group-item">
                <span class="badge"><?php echo $this->qtde_total ?></span>
                Total:&nbsp;&nbsp;
            </li>
        </ul>
    </td>
    <td>
        
    </td>
</table>

    <a href="<?=$this->url('dashboard/default', array('controller' => 'lista-de-convidados', 'action' => 'adicionar-convidado'))?>" >
    <div>
        <span class="glyphicon glyphicon-plus btnDireita gi-2x" title="Adicionar Convidado"></span>        
    </div>
</a>


<br class="brBoth"><br>
<table class="table table-hover">
    <tr class="topoTabLista">
        <td><img alt="Varios check" title="clique aqui para marcar todos os convidados" src="<?php echo $this->basePath('img/multiplosCheck.png') ?>" ></td>
        <td>Nome</td>
        <td>Email</td>
        <td>Adultos</td>
        <td>Crianças</td>
        <td>Ações</td>
    </tr>
    <?php foreach ($this->lista as $convidado): ?>
    <tr>
        <td><input type="checkbox"></label></td>
        <td><?php echo $convidado->getNome() ?></td>
        <td><?php echo $convidado->getEmail() ?></td>
        <td><?php echo $convidado->getQtdeAdultos() ?></td>
        <td><?php echo $convidado->getQtdeCriancas() ?></td>
        <td>
            <span class="glyphicon glyphicon-pencil editarClIco"><span> | 
            <span class="glyphicon glyphicon-envelope enviarClIco"><span> | 
            <a href="<?=$this->url('route1', array('action' => 'deletar-convidado', 'id' => $convidado->getId()))?>"><span class="glyphicon glyphicon-trash excluirClIco"></a> <span>
        </td>
    </tr>
    <?php endforeach; ?>
</table>
<a href="<?=$this->url('dashboard/default', array('controller' => 'lista-de-convidados', 'action' => 'adicionar-convidado'))?>" >
    <div>
        <span class="glyphicon glyphicon-plus btnDireita gi-2x" title="Adicionar Convidado"></span>        
    </div>
</a>