<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('euCasando')?>
        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                ->prependStylesheet($this->basePath('css/estilos.css'))
                ?>

        <!-- Scripts -->
        <?php echo $this->losHeadScript()
                ->appendJquery()
                ->appendChosen();
            echo $this->losHeadLink()
                ->appendBootstrap()
                ->appendFontAwesome()
                ->appendChosen();
        ; ?>

    </head>
    <body>
        <div class="container">
            <nav class="navbar navbar-default">
                <div class="container-fluid">
                  <!-- Brand and toggle get grouped for better mobile display -->
                  <div class="navbar-header">
                    <a class="navbar-brand" href="<?php echo $this->url('dashboard/default', array('controller' => 'index', 'action' => 'index')); ?>">
                        <img alt="Brand" src="<?php echo $this->basePath('img/logo.png') ?>" width="50">
                    </a>
                  </div>
                  <!-- Collect the nav links, forms, and other content for toggling -->
                  <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                    <ul class="nav navbar-nav">
                      <li class="active"><a href="#">Link <span class="sr-only">(current)</span></a></li>
                      <li><a href="#">Link</a></li>
                    </ul>

                    <ul class="nav navbar-nav navbar-right">
                      <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><span class="glyphicon glyphicon-user"></span>&nbsp;&nbsp;Alice Albuquerque<span class="caret"></span></a>
                        <ul class="dropdown-menu">
                          <li><a href="#">Perfil</a></li>
                          <li><a href="#">Plano</a></li>
                          <li><a href="#">Dados Bancários</a></li>
                          <li><a href="#">Visitar Site</a></li>
                          <li role="separator" class="divider"></li>
                          <li><a href="#">Sair</a></li>
                        </ul>
                      </li>
                    </ul>
                  </div><!-- /.navbar-collapse -->
                </div><!-- /.container-fluid -->
            </nav>
            <div class="row">
                <div class="col-md-3">
                    <?
                    $controllerNome = $this->layout()->controllerNome;
                    echo $this->partial('dashboard/partials/menu-lateral', array('menu' => $controllerNome));
                    ?>
                </div>
                <div class="col-md-9">
                    <?php echo $this->content; ?>
                </div>
            </div>
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
    </body>
</html>
