<ol class="breadcrumb">
    <li><a href="<?=$this->url('application/default', array('controller' => 'index'))?>">Eu casando</a></li>
    <li><a href="#" class="active">Espaço Disponível</a></li>
</ol>
<br>
Você tem direito a 15mb de espaço no servidor para construção do site.
<br><br>
<div class="progress">
    <div class="progress-bar progress-bar-striped" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" style="width: 60%;">
      60%
    </div>
</div>
<div class="espaco-livre">6mb livres de 15mb</div>